# Basic
title: MegaMUä¸ªäººç«™
subtitle: æ¬¢è¿å…‰ä¸´
description: è½æ—¥é»„æ²™  ç™½å¸†ç§‹æ°´  ä½ å¯çŸ¥è°çš„è®°å¿†åœ¨æ—¶ç©ºé‡Œé£ï¼Ÿ
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: MegaMU
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Coding & life
url: "https://megamu.icu/"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MzgwMC8zMDI3Mw  # https://www.livere.com
    # disqus: 
    # uyan: 
    gitalk: 
        clientId: 'c8a09d2aff45e43ec434'
        clientSecret: '6d0ef216e25180f92296c429ff96ce7e49390705'
        repo: 'https://github.com/SirMegaMU/sirmegamu.github.io'
        username: 'sirmegamu'
# Social
social:
    # weibo: 7674937679
    github: SirMegaMU
    # zhihu: é£é›ªæ…¢å½’ç¨‹
    # juejin: 761297657137879
    # jianshu: 
    twitter: MegaMU666
    mail: sirmegamu@outlook.com
    codeforces: MegaMU
    feedspub: MegaMU
    steam: MegaMU666
    telegram: Mega_MU


# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 3a8212ed0e86bf4c4fc9d07c2026dcca

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: G-L7SHH7HQ7N
    host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: æ”¯æŒ, description: support, url: '/support'}
    - {title: å…³äº, description: about, url: '/about'}
    - {title: è¿·æ€, description: thoughts, url: '/thoughts'}
    - {title: å‹é“¾, description: friends, url: '/friends'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
